FROM codeallergy/ubuntu-golang as builder

ARG VERSION
ARG BUILD

WORKDIR /go/src/github.com/codeallergy/sprintframework
ADD . .

RUN go build -o /sprint -v -ldflags "-X main.Version=${VERSION} -X main.Build=${BUILD}"

CMD ["cat", "/sprint"]

